"""Add cedula codigo regional to user

Revision ID: 4372a28e665b
Revises: 2627546b025d
Create Date: 2026-05-21 02:00:19.732798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4372a28e665b'
down_revision: Union[str, Sequence[str], None] = '2627546b025d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cedula', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('codigo_empleado', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('regional', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=True)
    op.create_index(op.f('ix_usuarios_codigo_empleado'), 'usuarios', ['codigo_empleado'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_codigo_empleado'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.drop_column('usuarios', 'regional')
    op.drop_column('usuarios', 'codigo_empleado')
    op.drop_column('usuarios', 'cedula')
    # ### end Alembic commands ###
