graph TD
    A[Regionales] --> B[Usuarios]
    A --> C[Clientes]
    B --> D[Items/Catalogo]
    B --> E[Usuarios]
    D --> F[Activos]
    D --> G[Stock Bulk]
    C --> H[Proyectos]
    F --> I[Garantias]
    F --> J[Movimientos]
    H --> J
