repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: ['--max-warnings=0']
        additional_dependencies:
          - eslint@^8.57.0
          - '@typescript-eslint/eslint-plugin@^7.2.0'
          - '@typescript-eslint/parser@^7.2.0'
          - eslint-plugin-react-hooks@^4.6.0
          - eslint-plugin-react-refresh@^0.4.6
