# -*- mode: python ; coding: utf-8 -*-
import os
import sys

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app', 'app'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops.auto',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.middleware',
        'fastapi',
        'sqlalchemy',
        'sqlalchemy.ext.asyncio',
        'sqlalchemy.orm',
        'sqlalchemy.sql.default_comparator',
        'pydantic',
        'pydantic_settings',
        'passlib',
        'passlib.handlers.bcrypt',
        'jose',
        'apscheduler',
        'apscheduler.triggers.interval',
        'reportlab',
        'reportlab.platypus',
        'reportlab.lib',
        'openpyxl',
        'xlsxwriter',
        'pandas',
        'numpy',
        'yaml',
        'python_multipart',
        'email_validator',
        'asyncio',
        'aiomysql',
        'asyncpg',
        'pymysql',
        'greenlet',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'sympy',
        'PIL',
        'cv2',
        'notebook',
        'ipython',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    contents_directory='.',
)
