# -*- mode: python ; coding: utf-8 -*-
import os
import sys

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app', 'app'),
        ('.env', '.'),
    ],
    hiddenimports=[
        # Core Framework
        'fastapi',
        'fastapi.responses',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.middleware.gzip',
        'fastapi.staticfiles',
        'fastapi.security',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.middleware',
        'uvicorn.middleware.proxy_headers',
        'pydantic',
        'pydantic_core',
        'pydantic_settings',
        'starlette',
        'starlette.concurrency',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.middleware.gzip',
        'starlette.responses',

        # Database
        'sqlalchemy',
        'sqlalchemy.ext',
        'sqlalchemy.ext.asyncio',
        'sqlalchemy.orm',
        'sqlalchemy.sql',
        'sqlalchemy.sql.default_comparator',
        'sqlalchemy.sql.elements',
        'sqlalchemy.sql.schema',
        'sqlalchemy.sql.compiler',
        'sqlalchemy.dialects',
        'sqlalchemy.dialects.postgresql',
        'sqlalchemy.dialects.postgresql.asyncpg',
        'sqlalchemy.dialects.mysql',
        'sqlalchemy.dialects.mysql.aiomysql',
        'alembic',
        'alembic.config',
        'alembic.script',
        'pymysql',
        'pymysql',
        'pymysql.constants',
        'pymysql.constants.CLIENT',
        'pymysql.converters',
        'aiomysql',
        'asyncpg',
        'asyncpg.pgproto',
        'asyncpg.protocol',
        'greenlet',
        'mako',
        'mako',
        'mako.template',
        'mako.runtime',

        # Security
        'jose',
        'jose.jwt',
        'jose.jws',
        'jose.jwk',
        'jose.utils',
        'jose.constants',
        'jose.exceptions',
        'passlib',
        'passlib.handlers',
        'passlib.handlers.bcrypt',
        'bcrypt',
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'python_multipart',
        'multipart',
        'email_validator',
        'ecdsa',
        'pyasn1',
        'rsa',

        # Data Processing & Reports
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'numpy',
        'openpyxl',
        'openpyxl.drawing',
        'openpyxl.drawing.image',
        'openpyxl.styles',
        'openpyxl.utils',
        'xlsxwriter',
        'reportlab',
        'reportlab.platypus',
        'reportlab.platypus.flowables',
        'reportlab.lib',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.lib.pagesizes',
        'reportlab.lib.colors',
        'reportlab.lib.utils',
        'reportlab.graphics',
        'reportlab.pdfbase',
        'reportlab.pdfbase._fontdata',
        'PIL',
        'PIL',
        'PIL._imaging',
        'PIL.Image',
        'PIL.JpegImagePlugin',
        'PIL.PngImagePlugin',
        'et_xmlfile',

        # Utilities
        'dotenv',
        'dateutil',
        'six',
        'typing_extensions',
        'certifi',
        'charset_normalizer',
        'idna',
        'anyio',
        'h11',
        'watchfiles',
        'websockets',
        'click',
        'colorama',
        'pygments',
        'packaging',

        # Rate Limiting
        'slowapi',
        'slowapi.extension',
        'slowapi.util',
        'slowapi.errors',
        'limits',

        # Scheduled Tasks
        'apscheduler',
        'apscheduler.schedulers',
        'apscheduler.schedulers.asyncio',
        'apscheduler.triggers',
        'apscheduler.triggers.interval',
        'apscheduler.jobstores',
        'apscheduler.executors',
        'tzlocal',

        # Logging
        'pythonjsonlogger',
        'pythonjsonlogger.jsonlogger',

        # Monitoring
        'psutil',

        # Async DB
        'asyncio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'sympy',
        'cv2',
        'notebook',
        'ipython',
        'pytest',
        'pytest_asyncio',
        'pytest_cov',
        'pytest_mock',
        'coverage',
        'httpx',
        'httpcore',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SIGAI-SES',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    contents_directory='.',
    icon='app\\static\\web\\favicon.ico',
)
