stateDiagram-v2
 [*] --> REGISTRADO
 REGISTRADO --> ENVIADO_PROVEEDOR
 ENVIADO_PROVEEDOR --> RECIBIDO_PROVEEDOR
 RECIBIDO_PROVEEDOR --> RESUELTO
 RECIBIDO_PROVEEDOR --> REEMPLAZADO
 RESUELTO --> ENTREGADO_A_CLIENTE
 REEMPLAZADO --> ENTREGADO_A_CLIENTE
 REEMPLAZADO --> STOCK
