"""Initial migration

Revision ID: 2627546b025d
Revises: 
Create Date: 2026-05-21 01:52:22.288409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2627546b025d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actas_entrega', 'fecha_entrega',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('actas_entrega', 'firma_tecnico_blob',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_actas_entrega_id_acta'), 'actas_entrega', ['id_acta'], unique=False)
    op.alter_column('activos', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.create_index(op.f('ix_activos_id_activo'), 'activos', ['id_activo'], unique=False)
    op.alter_column('audit_logs', 'valor_anterior',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'valor_nuevo',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'fecha_accion',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_audit_logs_id_log'), 'audit_logs', ['id_log'], unique=False)
    op.alter_column('clientes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_clientes_id_cliente'), 'clientes', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_detalles_acta_entrega_id_detalle'), 'detalles_acta_entrega', ['id_detalle'], unique=False)
    op.create_index(op.f('ix_garantias_id_garantia'), 'garantias', ['id_garantia'], unique=False)
    op.alter_column('items', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_items_id_item'), 'items', ['id_item'], unique=False)
    op.alter_column('movimientos_inventario', 'fecha_movimiento',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_movimientos_inventario_id_movimiento'), 'movimientos_inventario', ['id_movimiento'], unique=False)
    op.alter_column('proveedores', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_proveedores_id_proveedor'), 'proveedores', ['id_proveedor'], unique=False)
    op.alter_column('proyectos', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_proyectos_id_proyecto'), 'proyectos', ['id_proyecto'], unique=False)
    op.alter_column('usuarios', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('email'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_index(op.f('email'), 'usuarios', ['email'], unique=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_proyectos_id_proyecto'), table_name='proyectos')
    op.alter_column('proyectos', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_proveedores_id_proveedor'), table_name='proveedores')
    op.alter_column('proveedores', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_movimientos_inventario_id_movimiento'), table_name='movimientos_inventario')
    op.alter_column('movimientos_inventario', 'fecha_movimiento',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_items_id_item'), table_name='items')
    op.alter_column('items', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_garantias_id_garantia'), table_name='garantias')
    op.drop_index(op.f('ix_detalles_acta_entrega_id_detalle'), table_name='detalles_acta_entrega')
    op.drop_index(op.f('ix_clientes_id_cliente'), table_name='clientes')
    op.alter_column('clientes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_audit_logs_id_log'), table_name='audit_logs')
    op.alter_column('audit_logs', 'fecha_accion',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('audit_logs', 'valor_nuevo',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'valor_anterior',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_activos_id_activo'), table_name='activos')
    op.alter_column('activos', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.drop_index(op.f('ix_actas_entrega_id_acta'), table_name='actas_entrega')
    op.alter_column('actas_entrega', 'firma_tecnico_blob',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('actas_entrega', 'fecha_entrega',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###
