"""add alert.solucion column

Revision ID: e9c3b6a1f2b4
Revises: 02e89ad94861
Create Date: 2026-07-01 18:57:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9c3b6a1f2b4'
down_revision: Union[str, Sequence[str], None] = '02e89ad94861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: add solucion column to alerts"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('solucion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: remove solucion column from alerts"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'solucion')
    # ### end Alembic commands ###
